name: Run the Test Suite

on:
  push:
    branches: [main]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v5.0.0

    - name: Set up Node.js
      uses: actions/setup-node@v6.0.0
      with:
        node-version: 20

    - name: Install dependencies (packages)
      run: npm ci

    - name: Generate Prisma Client (Accelerate)
      run: npx prisma generate --accelerate
      env:
        DATABASE_URL: ${{ secrets.TEST_DB }}

    - name: Run tests
      run: npx jest --runInBand
      env:
        DATABASE_URL: ${{ secrets.TEST_DB }}
  
        

    
